---
apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource
metadata:
  name: default-serviceaccount-non-renewable
spec:
  settings:
    adopt: true
  tenantSelector:
    matchLabels:
      energy: non-renewable
  dependsOn:
    - name: non-renewable-pull-secrets
  resyncPeriod: 60s
  resources:
    - additionalMetadata:
        labels:
          test: 'test'
        annotations:
          k8s.company.com/cost-center: "inv-120"
    - context:
        resources:
          - index: secrets
            apiVersion: v1
            kind: Secret
            namespace: "capsule-system"
            selector:
              matchLabels:
                energy: non-renewable

      generators:
        - template: |
            ---
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: default
            {{ "{{- if $.secrets }}" }}
            imagePullSecrets:
            {{ "{{- range $.secrets }}" }}
              - name: {{ "{{ .metadata.name }}" }}
            {{ "{{- end }}" }}
            {{ "{{- end }}" }}
