---
apiVersion: v1
kind: Secret
metadata:
  name: quay-imagepullsecret-non-renewable
  namespace: capsule-system
  labels:
    energy: non-renewable
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmV4YW1wbGUuY29tIjp7InVzZXJuYW1lIjoiZHVtbXkiLCJwYXNzd29yZCI6ImR1bW15IiwiYXV0aCI6IlpIVnRiWGs2WkhWdGJYaz0iLCJlbWFpbCI6ImR1bW15QGV4YW1wbGUuY29tIn19fQ==
---
apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource
metadata:
  name: non-renewable-pull-secrets
spec:
  tenantSelector:
    matchLabels:
      energy: non-renewable
  resyncPeriod: 60s
  resources:
    - namespacedItems:
        - apiVersion: v1
          kind: Secret
          namespace: capsule-system
          selector:
            matchLabels:
              energy: non-renewable
