---
apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource
metadata:
  name: default-serviceaccount-renewable
spec:
  tenantSelector:
    matchLabels:
      energy: renewable
  dependsOn:
    - name: renewable-pull-secrets
  resyncPeriod: 60s
  resources:
    - context:
        resources:
          - index: secrets
            apiVersion: v1
            kind: Secret
            namespace: "capsule-system"
            selector:
              matchLabels:
                energy: renewable
      generators:
        - template: |
            ---
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: show-context
            data:
              context.yaml: |
                "{{ "{{- toYAML $ | nindent 4 }}" }}"
        # - template: |
        #     ---
        #     apiVersion: v1
        #     kind: ServiceAccount
        #     metadata:
        #     name: default
        #     imagePullSecrets:
        #         - name: "{{ "{{ .name }}" }}"
