---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-imagepullsecret-renewable
  namespace: capsule-system
  labels:
    energy: renewable
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuZXhhbXBsZS5jb20iOnsidXNlcm5hbWUiOiJkdW1teSIsInBhc3N3b3JkIjoiZHVtbXkiLCJhdXRoIjoiWkhWdGJYazZaSFZ0YlhrPSIsImVtYWlsIjoiZHVtbXlAZXhhbXBsZS5jb20ifX19
---
apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource
metadata:
  name: renewable-pull-secrets
spec:
  tenantSelector:
    matchLabels:
      energy: renewable
  resyncPeriod: 60s
  resources:
    - namespacedItems:
        - apiVersion: v1
          kind: Secret
          namespace: capsule-system
          selector:
            matchLabels:
              energy: renewable
